.TH XENTA-SOFTWARE-CENTER 1 "January 2012"

.SH NAME
xenta-software-center \- Utility for browsing, installing, removing applications on Xenta OS

.SH DESCRIPTION
.B xenta-software-center
lets you browse and install thousands of applications available for Xenta OS. You can view available applications by category, or search quickly by name or description. You can also examine the applications already installed, and remove those you no longer need.

This center was especially optimised for Xenta OS, but you have access to the same free applications than on Ubuntu Software Center.

To install or remove software using the Center, you need administrator access on the computer.

.SH AUTHORS
This manual page was written by Julien Lavergne for the Ubuntu Project, but may be used by others. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-2.
