#!/usr/bin/env python
#       Copyright (c)   Dindin Hernawan <root@dev.xentaos.org>
#                       Stephen Smally <stephen.smally@gmail.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#

import sys
import urllib
import os

args = sys.argv

if len(args) == 3:
    pkg = args[1]
    where = args[2]
    if not os.path.exists(where+pkg):
        try:
            urllib.urlretrieve(
                "http://screenshots.ubuntu.com/screenshot/%s" % pkg, where+pkg)
        except IOError:
            print("Check your internet connection")
            sys.exit()
    print("downloaded")

else:
    print("Usage: xenta-software-center-download-scrot PKG-NAME OUPUT-DIR")
